/**
 * GENERATED FILE — do not edit.
 *
 * Produced by `npm run generate` from `contracts/openapi.v1.json`, the same
 * contract the firmendata TypeScript and Python SDKs generate their types
 * from. Edit the API, re-export the contract, re-run the generator.
 *
 * 33 filters, covering every query parameter of
 * GET /v1/companies/search except `q` and `limit`, which the node exposes as
 * top-level fields.
 */

import type { INodeProperties } from 'n8n-workflow';

export const searchFilters: INodeProperties[] = [
  {
    displayName: 'City',
    name: 'city',
    type: 'string',
    default: '',
    placeholder: 'value1,value2',
    description: 'Registered seat city, spelled as in the register. Comma-separate for several; umlauts are optional (Munchen matches München).',
    routing: { request: { qs: { city: '={{$value || undefined}}' } } },
  },
  {
    displayName: 'Company Name',
    name: 'companyName',
    type: 'string',
    default: '',
    description: 'Company name prefix. The legal-form suffix counts, so "Bosch GmbH" narrows against "Bosch".',
    routing: { request: { qs: { company_name: '={{$value || undefined}}' } } },
  },
  {
    displayName: 'Cursor',
    name: 'cursor',
    type: 'string',
    default: '',
    description: 'Pagination cursor — pass pagination.next_cursor from a previous response to fetch the next page',
    routing: { request: { qs: { cursor: '={{$value || undefined}}' } } },
  },
  {
    displayName: 'Employee Count Max',
    name: 'employeeCountMax',
    type: 'number',
    typeOptions: { minValue: 0 },
    default: 0,
    description: 'Maximum reported employee count. Optional for most legal forms — see Employee Count Min.',
    routing: { request: { qs: { employee_count_max: '={{$value || undefined}}' } } },
  },
  {
    displayName: 'Employee Count Min',
    name: 'employeeCountMin',
    type: 'number',
    typeOptions: { minValue: 0 },
    default: 0,
    description: 'Minimum reported employee count. Reporting headcount is optional for most German legal forms, so expect small result sets.',
    routing: { request: { qs: { employee_count_min: '={{$value || undefined}}' } } },
  },
  {
    displayName: 'Family Managed',
    name: 'familyManaged',
    type: 'boolean',
    default: false,
    description: 'Whether to restrict to companies where two or more members of one family hold an ownership or governing role (true), or where the people on record are unrelated (false)',
    routing: { request: { qs: { family_managed: '={{$value || undefined}}' } } },
  },
  {
    displayName: 'Federal State',
    name: 'bundesland',
    type: 'multiOptions',
    default: [],
    options: [
      { name: 'Baden-Württemberg', value: 'Baden-Württemberg' },
      { name: 'Bayern', value: 'Bayern' },
      { name: 'Berlin', value: 'Berlin' },
      { name: 'Brandenburg', value: 'Brandenburg' },
      { name: 'Bremen', value: 'Bremen' },
      { name: 'Hamburg', value: 'Hamburg' },
      { name: 'Hessen', value: 'Hessen' },
      { name: 'Mecklenburg-Vorpommern', value: 'Mecklenburg-Vorpommern' },
      { name: 'Niedersachsen', value: 'Niedersachsen' },
      { name: 'Nordrhein-Westfalen', value: 'Nordrhein-Westfalen' },
      { name: 'Rheinland-Pfalz', value: 'Rheinland-Pfalz' },
      { name: 'Saarland', value: 'Saarland' },
      { name: 'Sachsen', value: 'Sachsen' },
      { name: 'Sachsen-Anhalt', value: 'Sachsen-Anhalt' },
      { name: 'Schleswig-Holstein', value: 'Schleswig-Holstein' },
      { name: 'Thüringen', value: 'Thüringen' },
    ],
    description: 'German federal state',
    routing: { request: { qs: { bundesland: '={{$value?.length ? $value.join(",") : undefined}}' } } },
  },
  {
    displayName: 'Fetch Realtime',
    name: 'fetchRealtime',
    type: 'boolean',
    default: false,
    description: 'Whether to also search the German registers live and add companies not yet indexed. Requires Search Query or Company Name, costs extra credits, and adds a few seconds.',
    routing: { request: { qs: { fetch_realtime: '={{$value || undefined}}' } } },
  },
  {
    displayName: 'Founded From',
    name: 'foundedFrom',
    type: 'dateTime',
    default: '',
    description: 'Earliest founding date (inclusive, YYYY-MM-DD)',
    routing: { request: { qs: { founded_from: '={{$value || undefined}}' } } },
  },
  {
    displayName: 'Founded To',
    name: 'foundedTo',
    type: 'dateTime',
    default: '',
    description: 'Latest founding date (inclusive, YYYY-MM-DD)',
    routing: { request: { qs: { founded_to: '={{$value || undefined}}' } } },
  },
  {
    displayName: 'Founder Led',
    name: 'founderLed',
    type: 'boolean',
    default: false,
    description: 'Whether to restrict to companies where a person holding an ownership or governing role at first registration is still in office (true), or where the founding officers have all been replaced (false)',
    routing: { request: { qs: { founder_led: '={{$value || undefined}}' } } },
  },
  {
    displayName: 'Has Email',
    name: 'hasEmail',
    type: 'boolean',
    default: false,
    description: 'Whether to restrict to companies with (true) or without (false) a known email',
    routing: { request: { qs: { has_email: '={{$value || undefined}}' } } },
  },
  {
    displayName: 'Has Website',
    name: 'hasWebsite',
    type: 'boolean',
    default: false,
    description: 'Whether to restrict to companies with (true) or without (false) a known website',
    routing: { request: { qs: { has_website: '={{$value || undefined}}' } } },
  },
  {
    displayName: 'Industry',
    name: 'industrySlug',
    type: 'multiOptions',
    default: [],
    options: [
      { name: 'Automotive', value: 'automotive' },
      { name: 'Chemicals', value: 'chemicals' },
      { name: 'Construction', value: 'construction' },
      { name: 'Consulting', value: 'consulting' },
      { name: 'Education', value: 'education' },
      { name: 'Energy', value: 'energy' },
      { name: 'Financial Services', value: 'financial_services' },
      { name: 'Food', value: 'food' },
      { name: 'Healthcare', value: 'healthcare' },
      { name: 'Holdings', value: 'holdings' },
      { name: 'Hospitality', value: 'hospitality' },
      { name: 'Insurance', value: 'insurance' },
      { name: 'Legal', value: 'legal' },
      { name: 'Logistics', value: 'logistics' },
      { name: 'Manufacturing', value: 'manufacturing' },
      { name: 'Media', value: 'media' },
      { name: 'Mining', value: 'mining' },
      { name: 'Public Sector', value: 'public_sector' },
      { name: 'Technology', value: 'technology' },
      { name: 'Telecom', value: 'telecom' },
      { name: 'Trade', value: 'trade' },
    ],
    description: 'High-level firmendata industry category',
    routing: { request: { qs: { industry_slug: '={{$value?.length ? $value.join(",") : undefined}}' } } },
  },
  {
    displayName: 'Industry Code (WZ 2025)',
    name: 'wz2025Code',
    type: 'string',
    default: '',
    placeholder: 'value1,value2',
    description: 'WZ 2025 industry code at any level: 62, 62.1, 62.10 or 62.10.3. Note these are WZ 2025, not WZ 2008 — an old code such as 62.01 matches nothing. Use Industry for a plain-language picker instead',
    routing: { request: { qs: { wz_2025_code: '={{$value || undefined}}' } } },
  },
  {
    displayName: 'Legal Form',
    name: 'rechtsform',
    type: 'multiOptions',
    default: [],
    options: [
      { name: 'AG', value: 'AG' },
      { name: 'AG & Co. KG', value: 'AG & Co. KG' },
      { name: 'Ausländische Rechtsform', value: 'ausländische Rechtsform' },
      { name: 'Ausländische Rechtsform (GnR)', value: 'ausländische Rechtsform (GnR)' },
      { name: 'Ausländische Rechtsform (HRA)', value: 'ausländische Rechtsform (HRA)' },
      { name: 'Ausländische Rechtsform (HRB)', value: 'ausländische Rechtsform (HRB)' },
      { name: 'Ausländische Rechtsform (PR)', value: 'ausländische Rechtsform (PR)' },
      { name: 'e.K.', value: 'e.K.' },
      { name: 'e.V.', value: 'e.V.' },
      { name: 'eG', value: 'eG' },
      { name: 'eG & Co. KG', value: 'eG & Co. KG' },
      { name: 'eGbR', value: 'eGbR' },
      { name: 'EWIV', value: 'EWIV' },
      { name: 'gGmbH', value: 'gGmbH' },
      { name: 'GmbH', value: 'GmbH' },
      { name: 'GmbH & Co. KG', value: 'GmbH & Co. KG' },
      { name: 'GmbH & Co. OHG', value: 'GmbH & Co. OHG' },
      { name: 'KG', value: 'KG' },
      { name: 'KGaA', value: 'KGaA' },
      { name: 'Ltd. & Co. KG', value: 'Ltd. & Co. KG' },
      { name: 'OHG', value: 'OHG' },
      { name: 'PartG', value: 'PartG' },
      { name: 'SCE', value: 'SCE' },
      { name: 'SE', value: 'SE' },
      { name: 'SE & Co. KG', value: 'SE & Co. KG' },
      { name: 'Sonstige Juristische Person', value: 'sonstige juristische Person' },
      { name: 'Sonstige Juristische Person (HRA)', value: 'sonstige juristische Person (HRA)' },
      { name: 'Stiftung & Co. KG', value: 'Stiftung & Co. KG' },
      { name: 'UG', value: 'UG' },
      { name: 'UG & Co. KG', value: 'UG & Co. KG' },
      { name: 'VVaG', value: 'VVaG' },
    ],
    description: 'German legal form',
    routing: { request: { qs: { rechtsform: '={{$value?.length ? $value.join(",") : undefined}}' } } },
  },
  {
    displayName: 'Legal Status',
    name: 'legalStatus',
    type: 'multiOptions',
    default: [],
    options: [
      { name: 'Active', value: 'active' },
      { name: 'Deleted', value: 'deleted' },
      { name: 'Dissolved', value: 'dissolved' },
      { name: 'In Liquidation', value: 'in_liquidation' },
      { name: 'Insolvent', value: 'insolvent' },
    ],
    description: 'Company lifecycle status, resolved from the merged Handelsregister (SI + CD) and Insolvenzbekanntmachungen timelines',
    routing: { request: { qs: { legal_status: '={{$value?.length ? $value.join(",") : undefined}}' } } },
  },
  {
    displayName: 'LEI',
    name: 'leiCode',
    type: 'string',
    default: '',
    description: 'Exact 20-character Legal Entity Identifier, for companies that hold one',
    routing: { request: { qs: { lei_code: '={{$value || undefined}}' } } },
  },
  {
    displayName: 'Membership',
    name: 'membership',
    type: 'multiOptions',
    default: [],
    options: [
      { name: 'BaFin', value: 'BaFin' },
      { name: 'Bbh', value: 'bbh' },
      { name: 'LEI', value: 'LEI' },
      { name: 'Steuerberaterkammer', value: 'Steuerberaterkammer' },
      { name: 'Wirtschaftsprueferkammer', value: 'Wirtschaftsprueferkammer' },
    ],
    description: 'Companies listed in at least one of these external registries',
    routing: { request: { qs: { membership: '={{$value?.length ? $value.join(",") : undefined}}' } } },
  },
  {
    displayName: 'Person Name',
    name: 'personName',
    type: 'string',
    default: '',
    description: 'Name of a board member, shareholder or partner, current or historical',
    routing: { request: { qs: { person_name: '={{$value || undefined}}' } } },
  },
  {
    displayName: 'Profit Max',
    name: 'profitMax',
    type: 'number',
    default: 0,
    description: 'Maximum reported profit in EUR — negative values select loss-making companies',
    routing: { request: { qs: { profit_max: '={{$value || undefined}}' } } },
  },
  {
    displayName: 'Profit Min',
    name: 'profitMin',
    type: 'number',
    default: 0,
    description: 'Minimum reported profit in EUR. Only companies filing a full profit-and-loss statement have one.',
    routing: { request: { qs: { profit_min: '={{$value || undefined}}' } } },
  },
  {
    displayName: 'Register Court',
    name: 'registerCourt',
    type: 'options',
    default: 'Berlin (Charlottenburg)',
    options: [
      { name: 'Aachen', value: 'Aachen' },
      { name: 'Ahaus', value: 'Ahaus' },
      { name: 'Amberg', value: 'Amberg' },
      { name: 'Ansbach', value: 'Ansbach' },
      { name: 'Arnsberg', value: 'Arnsberg' },
      { name: 'Aschaffenburg', value: 'Aschaffenburg' },
      { name: 'Augsburg', value: 'Augsburg' },
      { name: 'Aurich', value: 'Aurich' },
      { name: 'Bad Hersfeld', value: 'Bad Hersfeld' },
      { name: 'Bad Homburg v.d.H.', value: 'Bad Homburg v.d.H.' },
      { name: 'Bad Kreuznach', value: 'Bad Kreuznach' },
      { name: 'Bad Oeynhausen', value: 'Bad Oeynhausen' },
      { name: 'Bamberg', value: 'Bamberg' },
      { name: 'Bayreuth', value: 'Bayreuth' },
      { name: 'Berlin (Charlottenburg)', value: 'Berlin (Charlottenburg)' },
      { name: 'Bielefeld', value: 'Bielefeld' },
      { name: 'Bocholt', value: 'Bocholt' },
      { name: 'Bochum', value: 'Bochum' },
      { name: 'Bonn', value: 'Bonn' },
      { name: 'Borken', value: 'Borken' },
      { name: 'Braunschweig', value: 'Braunschweig' },
      { name: 'Bremen', value: 'Bremen' },
      { name: 'Bremerhaven', value: 'Bremerhaven' },
      { name: 'Chemnitz', value: 'Chemnitz' },
      { name: 'Coburg', value: 'Coburg' },
      { name: 'Coesfeld', value: 'Coesfeld' },
      { name: 'Cottbus', value: 'Cottbus' },
      { name: 'Darmstadt', value: 'Darmstadt' },
      { name: 'Deggendorf', value: 'Deggendorf' },
      { name: 'Dortmund', value: 'Dortmund' },
      { name: 'Dresden', value: 'Dresden' },
      { name: 'Duisburg', value: 'Duisburg' },
      { name: 'Dülmen', value: 'Dülmen' },
      { name: 'Düren', value: 'Düren' },
      { name: 'Düsseldorf', value: 'Düsseldorf' },
      { name: 'Eschwege', value: 'Eschwege' },
      { name: 'Essen', value: 'Essen' },
      { name: 'Flensburg', value: 'Flensburg' },
      { name: 'Frankfurt Am Main', value: 'Frankfurt am Main' },
      { name: 'Frankfurt/Oder', value: 'Frankfurt/Oder' },
      { name: 'Freiburg', value: 'Freiburg' },
      { name: 'Friedberg', value: 'Friedberg' },
      { name: 'Fritzlar', value: 'Fritzlar' },
      { name: 'Fulda', value: 'Fulda' },
      { name: 'Fürth', value: 'Fürth' },
      { name: 'Gelsenkirchen', value: 'Gelsenkirchen' },
      { name: 'Gießen', value: 'Gießen' },
      { name: 'Göttingen', value: 'Göttingen' },
      { name: 'Gronau', value: 'Gronau' },
      { name: 'Gütersloh', value: 'Gütersloh' },
      { name: 'Hagen', value: 'Hagen' },
      { name: 'Hamburg', value: 'Hamburg' },
      { name: 'Hamm', value: 'Hamm' },
      { name: 'Hanau', value: 'Hanau' },
      { name: 'Hannover', value: 'Hannover' },
      { name: 'Hildesheim', value: 'Hildesheim' },
      { name: 'Hof', value: 'Hof' },
      { name: 'Homburg', value: 'Homburg' },
      { name: 'Ingolstadt', value: 'Ingolstadt' },
      { name: 'Iserlohn', value: 'Iserlohn' },
      { name: 'Jena', value: 'Jena' },
      { name: 'Kaiserslautern', value: 'Kaiserslautern' },
      { name: 'Kassel', value: 'Kassel' },
      { name: 'Kempten (Allgäu)', value: 'Kempten (Allgäu)' },
      { name: 'Kerpen', value: 'Kerpen' },
      { name: 'Kiel', value: 'Kiel' },
      { name: 'Kleve', value: 'Kleve' },
      { name: 'Koblenz', value: 'Koblenz' },
      { name: 'Köln', value: 'Köln' },
      { name: 'Königstein', value: 'Königstein' },
      { name: 'Korbach', value: 'Korbach' },
      { name: 'Krefeld', value: 'Krefeld' },
      { name: 'Landau', value: 'Landau' },
      { name: 'Landshut', value: 'Landshut' },
      { name: 'Langenfeld', value: 'Langenfeld' },
      { name: 'Lebach', value: 'Lebach' },
      { name: 'Leipzig', value: 'Leipzig' },
      { name: 'Lemgo', value: 'Lemgo' },
      { name: 'Limburg', value: 'Limburg' },
      { name: 'Lübeck', value: 'Lübeck' },
      { name: 'Lüdinghausen', value: 'Lüdinghausen' },
      { name: 'Ludwigshafen a.Rhein (Ludwigshafen)', value: 'Ludwigshafen a.Rhein (Ludwigshafen)' },
      { name: 'Lüneburg', value: 'Lüneburg' },
      { name: 'Mainz', value: 'Mainz' },
      { name: 'Mannheim', value: 'Mannheim' },
      { name: 'Marburg', value: 'Marburg' },
      { name: 'Memmingen', value: 'Memmingen' },
      { name: 'Merzig', value: 'Merzig' },
      { name: 'Mönchengladbach', value: 'Mönchengladbach' },
      { name: 'Montabaur', value: 'Montabaur' },
      { name: 'München', value: 'München' },
      { name: 'Münster', value: 'Münster' },
      { name: 'Neubrandenburg', value: 'Neubrandenburg' },
      { name: 'Neunkirchen', value: 'Neunkirchen' },
      { name: 'Neuruppin', value: 'Neuruppin' },
      { name: 'Neuss', value: 'Neuss' },
      { name: 'Nürnberg', value: 'Nürnberg' },
      { name: 'Offenbach Am Main', value: 'Offenbach am Main' },
      { name: 'Oldenburg (Oldenburg)', value: 'Oldenburg (Oldenburg)' },
      { name: 'Osnabrück', value: 'Osnabrück' },
      { name: 'Ottweiler', value: 'Ottweiler' },
      { name: 'Paderborn', value: 'Paderborn' },
      { name: 'Passau', value: 'Passau' },
      { name: 'Pinneberg', value: 'Pinneberg' },
      { name: 'Potsdam', value: 'Potsdam' },
      { name: 'Recklinghausen', value: 'Recklinghausen' },
      { name: 'Regensburg', value: 'Regensburg' },
      { name: 'Rostock', value: 'Rostock' },
      { name: 'Saarbrücken', value: 'Saarbrücken' },
      { name: 'Saarlouis', value: 'Saarlouis' },
      { name: 'Schleiden', value: 'Schleiden' },
      { name: 'Schweinfurt', value: 'Schweinfurt' },
      { name: 'Schwerin', value: 'Schwerin' },
      { name: 'Siegburg', value: 'Siegburg' },
      { name: 'Siegen', value: 'Siegen' },
      { name: 'St. Ingbert (St Ingbert)', value: 'St. Ingbert (St Ingbert)' },
      { name: 'St. Wendel (St Wendel)', value: 'St. Wendel (St Wendel)' },
      { name: 'Stadthagen', value: 'Stadthagen' },
      { name: 'Steinfurt', value: 'Steinfurt' },
      { name: 'Stendal', value: 'Stendal' },
      { name: 'Stralsund', value: 'Stralsund' },
      { name: 'Straubing', value: 'Straubing' },
      { name: 'Stuttgart', value: 'Stuttgart' },
      { name: 'Tostedt', value: 'Tostedt' },
      { name: 'Traunstein', value: 'Traunstein' },
      { name: 'Ulm', value: 'Ulm' },
      { name: 'Völklingen', value: 'Völklingen' },
      { name: 'Walsrode', value: 'Walsrode' },
      { name: 'Weiden I. D. OPf.', value: 'Weiden i. d. OPf.' },
      { name: 'Wetzlar', value: 'Wetzlar' },
      { name: 'Wiesbaden', value: 'Wiesbaden' },
      { name: 'Wittlich', value: 'Wittlich' },
      { name: 'Wuppertal', value: 'Wuppertal' },
      { name: 'Würzburg', value: 'Würzburg' },
      { name: 'Zweibrücken', value: 'Zweibrücken' },
    ],
    description: 'Registering court (Registergericht), by its canonical Handelsregister name',
    routing: { request: { qs: { register_court: '={{$value || undefined}}' } } },
  },
  {
    displayName: 'Register Number',
    name: 'registerNumber',
    type: 'number',
    typeOptions: { minValue: 1 },
    default: 0,
    description: 'Registernummer digits only, e.g. 123456 for HRB 123456. Numbers repeat across courts — add Register Court or Register Type to identify one company.',
    routing: { request: { qs: { register_number: '={{$value || undefined}}' } } },
  },
  {
    displayName: 'Register Type',
    name: 'registerType',
    type: 'options',
    default: 'HRB',
    options: [
      { name: 'GnR', value: 'GnR' },
      { name: 'GsR', value: 'GsR' },
      { name: 'HRA', value: 'HRA' },
      { name: 'HRB', value: 'HRB' },
      { name: 'PR', value: 'PR' },
      { name: 'VR', value: 'VR' },
    ],
    routing: { request: { qs: { register_type: '={{$value || undefined}}' } } },
  },
  {
    displayName: 'Revenue Max',
    name: 'revenueMax',
    type: 'number',
    default: 0,
    description: 'Maximum reported revenue in EUR. Filed by a minority of companies — see Revenue Min.',
    routing: { request: { qs: { revenue_max: '={{$value || undefined}}' } } },
  },
  {
    displayName: 'Revenue Min',
    name: 'revenueMin',
    type: 'number',
    default: 0,
    description: 'Minimum reported revenue in EUR. Most German companies file abridged accounts with no profit-and-loss statement, so revenue is the scarcest figure — use Total Assets Min to filter on size instead.',
    routing: { request: { qs: { revenue_min: '={{$value || undefined}}' } } },
  },
  {
    displayName: 'Sort',
    name: 'sort',
    type: 'options',
    default: 'revenue',
    options: [
      { name: 'Employee Count', value: 'employee_count' },
      { name: 'Name', value: 'name' },
      { name: 'Profit', value: 'profit' },
      { name: 'Revenue', value: 'revenue' },
      { name: 'Total Assets', value: 'total_assets' },
    ],
    description: 'Field to order results by',
    routing: { request: { qs: { sort: '={{$value || undefined}}' } } },
  },
  {
    displayName: 'Sort Direction',
    name: 'sortDirection',
    type: 'options',
    default: 'desc',
    options: [
      { name: 'Asc', value: 'asc' },
      { name: 'Desc', value: 'desc' },
    ],
    routing: { request: { qs: { sort_direction: '={{$value || undefined}}' } } },
  },
  {
    displayName: 'Succession Risk',
    name: 'successionRisk',
    type: 'boolean',
    default: false,
    description: 'Whether to restrict to founder-led companies whose oldest serving founder has reached 65 (true), or has not (false)',
    routing: { request: { qs: { succession_risk: '={{$value || undefined}}' } } },
  },
  {
    displayName: 'Tender Role',
    name: 'tenderRole',
    type: 'multiOptions',
    default: [],
    options: [
      { name: 'Buyer', value: 'buyer' },
      { name: 'Winner', value: 'winner' },
    ],
    description: 'Companies appearing in EU public-procurement notices (TED), in the selected role',
    routing: { request: { qs: { tender_role: '={{$value?.length ? $value.join(",") : undefined}}' } } },
  },
  {
    displayName: 'Total Assets Max',
    name: 'totalAssetsMax',
    type: 'number',
    default: 0,
    description: 'Maximum balance-sheet total in EUR. The widest-reaching size filter — see Total Assets Min.',
    routing: { request: { qs: { total_assets_max: '={{$value || undefined}}' } } },
  },
  {
    displayName: 'Total Assets Min',
    name: 'totalAssetsMin',
    type: 'number',
    default: 0,
    description: 'Minimum balance-sheet total in EUR. Every filing company publishes a balance sheet, so this is the widest-reaching size filter.',
    routing: { request: { qs: { total_assets_min: '={{$value || undefined}}' } } },
  },
];
